version: '0.1.{build}'

# Start builds on tags only (GitHub, BitBucket, GitLab, etc.)
# skip_non_tags: true

# Maximum number of concurrent jobs for the project (play nice)
max_jobs: 1

# Build environments
environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
      PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7.15"
      PYTHON_ARCH: "32"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
      PYTHON: "C:\\Python27-x64"
      PYTHON_VERSION: "2.7.15"
      PYTHON_ARCH: "32"
#    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
#      PYTHON: "C:\\Python27"
#      PYTHON_VERSION: "2.7.16"
#      PYTHON_ARCH: "32"
#    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
#      PYTHON: "C:\\Python27-x64"
#      PYTHON_VERSION: "2.7.16"
#      PYTHON_ARCH: "32"

build: false

init:
  - ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%

install:
  # Prepend newly installed Python to the PATH of this build (this cannot be
  # done from inside the powershell script as it would require to restart
  # the parent CMD process).
  - SET PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%

  # Check that we have the expected version and architecture for Python
  - python -c "import sys;print(sys.version)"

  # Install the project and its dependencies
  - pip install -e .[test]

test_script:
  # Run pytest with coverage and mock arcpy module
  - py.test tests --cov=gpf --mock_arcpy
