version: 1.0.{build}
image: Visual Studio 2015

build: false

environment:
  matrix:
    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7.14"
      PYTHON_ARCH: "32"

init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"

install:
  - "%PYTHON%/Scripts/pip.exe install -e .[tests]"

test_script:
  - "%PYTHON%/Scripts/pytest --mock_arcpy"
