version: 1.0.{build}
image: Visual Studio 2015

build: false

environment:
  matrix:
    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7.14"
      PYTHON_ARCH: "32"
    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7.15"
      PYTHON_ARCH: "32"
    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7.16"
      PYTHON_ARCH: "32"

init:
  - ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%

install:
  - set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%
  - pip install -e .[test]

test_script:
  - py.test tests
